### ISSUE TITLE
Does a docker image make sense and how would it look like?

### ISSUE THREAD

**Issue by mielvds** [zazuko/graph-explorer#12]
Would a container or a docker-compose (perhaps combined with https://github.com/lyrasis/docker-blazegraph) make sense for easy deployment? Not sure how it works with webpack.

**Comment by ktk** [comment]
Indeed to be discussed. What we do provide and will migrate to this repo is a plugin for our Trifid, see https://github.com/zazuko/trifid-plugin-ontodia. The idea there is that it's directly wired to the SPARQL endpoint provided by Trifid.

A standalone docker might also make sense, that could help bootstrapping it in environments where there is already an endpoint & access to it.

**Comment by semanticfire** [comment]
on top of an existing graph store offering I see the point, otherwise it seems like overkill to me?

**Comment by ludovicm67** [comment]
Graph Explorer is included by default in Trifid as a plugin.

So if you have a SPARQL endpoint, just run the following command by replacing `YOUR_SPARQL_ENDPOINT` with your real endpoint, and you will have something that works:

```sh
docker run --rm -e SPARQL_ENDPOINT_URL=https://YOUR_SPARQL_ENDPOINT -p 8080:8080 -it ghcr.io/zazuko/trifid:v5.0.2
```

And then open: http://localhost:8080/graph-explorer/

And you will be able to see Graph Explorer on top of your endpoint.
