### ISSUE TITLE
Bad performance on Jena Fulltext search due to query order

### ISSUE THREAD

**Issue by SimonBin** [zazuko/graph-explorer#22]

**Comment by semanticfire** [comment]
Thanks for the issue and the PR, I wonder if this should be in the generic settings, or that we should add a JenaSparqlDataProviderSettings ?
Fulltext search is something that is very implementation specific.

**Comment by SimonBin** [comment]
the point is that the Dataprovider has a hard coded query template which itself is assembled from configurable fragments. this PR simply gives the option to send the text query first
