### ISSUE TITLE
Importing graph-explorer via Unpkg returns an error

### ISSUE THREAD

**Issue by lolive** [zazuko/graph-explorer#25]
I would like to try graph-explorer in one of my web project.
In that project, files are served statically, so I do not have any NodeJS instance.
Usually, in that case, my html points the js libs at  Unpkg.com, which handles the delivery of a browser-ready version of libs I need, taking care of all the require/imports/modules mess.

I tried this HTML for graph-explorer: 
![image](https://github.com/zazuko/graph-explorer/assets/1871345/a1ae4b6c-4427-489f-a5a2-e8d271a7631e)

and got this error:
![image](https://github.com/zazuko/graph-explorer/assets/1871345/709a128f-d29c-46b6-9dce-ff6dd619aab7)

In parallel, I built locally from sources the file dist/graph-explorer.js, and pointing at my built version of the file from my .html returns the same error.

Any idea what I did wrong?

**Comment by lolive** [comment]
Note: adding React as script in the .html does not change the error.
![image](https://github.com/zazuko/graph-explorer/assets/1871345/ec3ffcf2-26e6-47ad-b0c8-1000839ac9ca)

**Comment by lolive** [comment]
Where as pointing at this built version makes no loading error: 
![image](https://github.com/zazuko/graph-explorer/assets/1871345/8866911b-c4a4-4270-8dc0-e60702ac6e8c)

**Comment by lolive** [comment]
It works with this: 
![image](https://github.com/zazuko/graph-explorer/assets/1871345/7d939f3d-964d-4b2f-9cee-a8b60aad82b4)

So my question becomes: why does the graph-explorer-full.min.js has, that the graph-explorer.js does not have?

**Comment by lolive** [comment]
Ok, the build of the minified version embed these libs:
![image](https://github.com/zazuko/graph-explorer/assets/1871345/02213a39-720e-48f9-999c-ee49e92e915c)

 whereas the build of the non-minified version does NOT embed these libs.

But then, back to my original question: how do you "give" React to the non-minified version when you load it? 
(not with a <script>, it seems)

**Comment by ludovicm67** [comment]
Hi @lolive!

Here is a full basic working example using unpkg for all imports, to illustrate how you can run the app:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Graph Explorer</title>

    <!-- Import "Font Awesome" for the icons -->
    <link
      rel="stylesheet"
      href="https://unpkg.com/font-awesome@4.7.0/css/font-awesome.min.css"
    />

    <!-- Basic style, just that we can see something -->
    <style>
      h1 {
        height: 42px;
      }

      #graph-explorer {
        width: 100%;
        height: calc(100vh - 100px);
      }
    </style>
  </head>
  <body>
    <h1>Graph Explorer demo</h1>

    <!-- This is where Graph Explorer will be mounted -->
    <div id="graph-explorer"></div>

    <!-- Import required libraries -->
    <script src="https://unpkg.com/graph-explorer@1.2.0/dist/graph-explorer-full.min.js"></script>
    <script src="https://unpkg.com/react@16.14.0/umd/react.production.min.js"></script>
    <script src="https://unpkg.com/react-dom@16.14.0/umd/react-dom.production.min.js"></script>

    <!-- Tell where to mount the app -->
    <script>
      // Some configuration for the Graph Explorer
      const graphExplorerConfig = {
        // Replace this with your own SPARQL endpoint
        endpointUrl: "https://ld.admin.ch/query",
        acceptBlankNodes: true,
        dataLabelProperty: "<http://schema.org/name> | rdfs:label",
        schemaLabelProperty: "<http://schema.org/name> | rdfs:label",
        language: "en",
        languages: [
          { code: "en", label: "English" },
          { code: "de", label: "German" },
          { code: "fr", label: "French" },
          { code: "it", label: "Italian" },
        ],
      };

      const SparqlDialect = GraphExplorer.OWLStatsSettings;
      SparqlDialect.dataLabelProperty = graphExplorerConfig.dataLabelProperty;
      SparqlDialect.schemaLabelProperty =
        graphExplorerConfig.schemaLabelProperty;

      const onWorkspaceMounted = async (workspace) => {
        if (!workspace) {
          return;
        }

        const model = workspace.getModel();

        model.importLayout({
          dataProvider: new GraphExplorer.SparqlDataProvider(
            {
              endpointUrl: graphExplorerConfig.endpointUrl,
              acceptBlankNodes: graphExplorerConfig.acceptBlankNodes,
              imagePropertyUris: ["http://xmlns.com/foaf/0.1/img"],
              queryMethod: GraphExplorer.SparqlQueryMethod.GET,
            },
            SparqlDialect
          ),
        });
      };

      const props = {
        ref: onWorkspaceMounted,
        languages: graphExplorerConfig.languages,
        language: graphExplorerConfig.language,
      };

      // Tell React to mount the app in the div with the id "graph-explorer"
      ReactDOM.render(
        React.createElement(GraphExplorer.Workspace, props),
        document.getElementById("graph-explorer")
      );
    </script>
  </body>
</html>
```

Some notes:

- You will need to import Font Awesome, to load the icons.
- React and React-DOM are required to mount the Graph Explorer app.
- You will need to write some custom script, in order to tell React where to mount the Graph Explorer app and to specify the endpoint to use. In this example, I set it to `https://ld.admin.ch/query`, but you will need to replace it with your own endpoint.
